/*
PHÂN TÍCH: 
	DO AND CÓ ĐỘ ƯU TIÊN CAO HƠN OR NÊN CÂU LỆNH ĐƯỢC HIỂU: 
    WHERE DISTRICT = 'QUẬN 1' OR (DISTRICT = 'QUẬN 3' AND RATING > 4.0);
    ==> LẤY TẤT CẢ QUẬN 1 KHÔNG QUAN TÂM ĐẾN RATING CÒN QUẬN 3 MỚI LỌC ĐIỀU KIỆN RATING > 4.0
*/
SELECT RESTAURANT_NAME, ADDRESS, RATING
FROM RESTAURANTS
WHERE (DISTRICT = 'QUẬN 1' OR DISTRICT = 'QUẬN 3') AND RATING > 4.0;
